### ISSUE TITLE
Drag & Drop on mobile

### ISSUE THREAD

**Issue by leijae** [nobleclem/jQuery-DragNDrop#1]
I'm not sure if you've addressed this anywhere, but this doesn't seem to work on mobile devices. I've only tried Brave Browser (Chromium) on Android.

This package works exactly as intended, and I like it for desktop based browsers... however it's been three years since an update, but are you planning on keeping this alive or should I be looking for an alternate solution?

**Comment by nobleclem** [comment]
The mobile issue should be resolved in the latest commit.  I don't have an android device to test but was able to test on iOS 15.1 Safari and Chrome.
